# Generated by Django 3.0 on 2019-12-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(help_text='Longitude of the sight')),
                ('Latitude', models.FloatField(help_text='Latitude of the sight')),
                ('Unique_Squirrel_Id', models.CharField(help_text='The unique ID of the squirrel', max_length=25)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Whether the sight is in the morning or late afternoon?', max_length=16)),
                ('Date', models.CharField(help_text='Date of the sighting', max_length=16)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), (None, '-')], help_text='Age', max_length=16)),
                ('Primary_Fur_Color', models.CharField(choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), (None, '-')], help_text='Fur color', max_length=16)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), (None, '-')], help_text='Location', max_length=128)),
                ('Specific_Location', models.CharField(blank=True, help_text='Additional notes to the location', max_length=128)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(blank=True, max_length=128)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
            ],
        ),
    ]
