# Generated by Django 3.0 on 2019-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191208_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), (None, '-'), ('?', '?')], help_text='Age of the squirrel', max_length=16),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Approaches',
            field=models.NullBooleanField(help_text='Approaches'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Chasing',
            field=models.NullBooleanField(help_text='Chasing'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Climbing',
            field=models.NullBooleanField(help_text='Climbing'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Date',
            field=models.DateField(help_text='The format is in yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Eating',
            field=models.NullBooleanField(help_text='Eating'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Foraging',
            field=models.NullBooleanField(help_text='Foraging'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Indifferent',
            field=models.NullBooleanField(help_text='Indifferent'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Kuks',
            field=models.NullBooleanField(help_text='Kuks'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), (None, '-')], help_text='Location', max_length=128),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Moans',
            field=models.NullBooleanField(help_text='Moans'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), (None, '-')], help_text='Fur color', max_length=16),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Quaas',
            field=models.NullBooleanField(help_text='Quaas'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Running',
            field=models.NullBooleanField(help_text='Running'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Runs_From',
            field=models.NullBooleanField(help_text='Runs_From'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Tail_Flags',
            field=models.NullBooleanField(help_text='Tail_Flags'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Tail_Twitches',
            field=models.NullBooleanField(help_text='Tail_Twitches'),
        ),
    ]
