# Generated by Django 3.0 on 2019-12-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191208_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='Date',
            field=models.DateField(blank=True, help_text='The format is in yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Other_Activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Whether the sight is in the morning or late afternoon?', max_length=16),
        ),
    ]
